# File: docker-compose.yml
# Author: Marc Bria UAB (marc.bria@uab.es)

services:
  db:
    image: ${DB_VERSION:-mariadb:11.8}
    container_name: "pkp_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-changeMePlease}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-pkp}"
      MYSQL_USER: "${MYSQL_USER:-pkp}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-changeMePlease}"
    networks:
      - ojs
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  app:
    image: '${IMAGE_SOURCE:-local}/${PKP_TOOL:-omp}:${PKP_VERSION:-3_3_0-20}'
    container_name: 'pkp_app_${COMPOSE_PROJECT_NAME:-demo}'
    hostname: '${COMPOSE_PROJECT_NAME:-demo}'
    environment:
      SERVERNAME: '${SERVERNAME:-journal.ghyampe.com}'
      DB_HOST: db
      DB_USER: '${MYSQL_USER:-pkp}'
      DB_PASSWORD: '${MYSQL_PASSWORD:-changeMePlease}'
      DB_NAME: '${MYSQL_DATABASE:-pkp}'
      FORCE_HTTPS: '0'
      HTTPS_HEADER: '0'
      OJS_CLI_INSTALL: 0
    volumes:
      - 'ojs-files:/var/www/html/files'
      - 'ojs-public:/var/www/html/public'
    networks:
      - ojs
    depends_on:
      - db
    restart: unless-stopped

networks:
  ojs: null

volumes:                                                                                                                                                                             
  db-data:      
  ojs-files:                                                                                                                                                                         
  ojs-public:
